openapi: 3.0.3
info:
  title: 'Noa api API de Posts y Análisis'
  description: 'Esta API proporciona acceso a posts y análisis.'
  version: 1.0.0
servers:
  -
    url: 'http://noa.test'
paths:
  /api/analyses:
    get:
      summary: 'API para gestionar análisis'
      operationId: aPIParaGestionarAnlisis
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n  \"data\": [\n    {\n      \"id\": 1,\n      \"title\": \"Análisis del mercado\",\n     \"content\": => \"Contenido del analisis que hemos creado anteriormente\",\n     \"score\": => \"75\"\n     \"console\": => \"Xbox\"\n     \"type\": => \"Review\"\n    }\n  ]\n}"
      tags:
        - Análisis
      security: []
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/posts:
    get:
      summary: 'API para gestionar posts'
      operationId: aPIParaGestionarPosts
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      title: 'Mi primer post'
                      content: 'Este es el contenido del post'
                      created_at: '2025-02-21 12:00:00'
                      updated_at: '2025-02-21 12:30:00'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        title: 'Mi primer post'
                        content: 'Este es el contenido del post'
                        created_at: '2025-02-21 12:00:00'
                        updated_at: '2025-02-21 12:30:00'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'Mi primer post'
                        content:
                          type: string
                          example: 'Este es el contenido del post'
                        created_at:
                          type: string
                          example: '2025-02-21 12:00:00'
                        updated_at:
                          type: string
                          example: '2025-02-21 12:30:00'
      tags:
        - Posts
      security: []
tags:
  -
    name: Análisis
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: Posts
    description: ''
